# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: My Blog
subtitle: ''
description: ''
keywords:
author: Your Name
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here
url: https://Eternity-sky.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_posts_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
  theme: tomorrow-night

prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Next Theme Config
theme_config:
  scheme: Gemini  # 最现代的布局方案
  darkmode: true  # 启用暗黑模式
  
  # 网站图标
  favicon:
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    
  # 菜单配置
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive

  # 侧边栏设置
  sidebar:
    position: left
    display: post

  # 社交链接
  social:
    GitHub: https://github.com/your-username || fab fa-github
    E-Mail: mailto:your-email@example.com || fa fa-envelope

  # 文章设置
  post_meta:
    item_text: true
    created_at: true
    updated_at: true
    categories: true
    tags: true

  # 代码高亮
  codeblock:
    copy_button: true
    highlight_theme: tomorrow-night

  # 动画效果
  motion:
    enable: true
    async: true

  # 返回顶部按钮
  back2top:
    enable: true
    sidebar: false
    scrollpercent: true

  # 阅读进度条
  reading_progress:
    enable: true
    position: top
    color: "#37c6c0"

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Eternity-sky/Eternity-sky.github.io.git
  branch: main
